### ISSUE TITLE
Hardcoded password

### ISSUE THREAD

**Issue by mpasserini** [fgci-org/ansible-role-slurm#1]
Ciao!
There's an hardcoded password in service.yml for the slurm user on the db =)

**Comment by martbhell** [comment]
Thanks!
This role is full of bad practices ;) 
Fortunately we don't use this script anywhere (yet).
Made the slurm mysql password a variable (as already mentioned in README) - 613b98812cb1ca69956d24a6491bb1bbebb9aecd
